// <auto-generated />
using System;
using CommunicationService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunicationService.Persistence.Migrations
{
    [DbContext(typeof(CommunicationDbContext))]
    [Migration("20251213175923_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunicationService.Domain.Entities.BusinessCommunicationSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("idx_settings_tenant");

                    b.ToTable("business_communication_settings", (string)null);
                });

            modelBuilder.Entity("CommunicationService.Domain.Entities.CommunicationEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("SourceEntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_entity_id");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_service");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("idx_events_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_events_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_events_tenant");

                    b.HasIndex("SourceService", "SourceEntityId")
                        .HasDatabaseName("idx_events_source");

                    b.ToTable("communication_events", (string)null);
                });

            modelBuilder.Entity("CommunicationService.Domain.Entities.MessageLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("EventId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_id");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_body");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recipient");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_key");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_logs_created");

                    b.HasIndex("EventId")
                        .HasDatabaseName("idx_logs_event");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_logs_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_logs_tenant");

                    b.ToTable("message_logs", (string)null);
                });

            modelBuilder.Entity("CommunicationService.Domain.Entities.MessageTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TemplateBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_body");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_key");

                    b.Property<string>("TenantId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variables")
                        .HasColumnType("jsonb")
                        .HasColumnName("variables");

                    b.HasKey("Id");

                    b.HasIndex("TemplateKey")
                        .HasDatabaseName("idx_templates_key");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_templates_tenant");

                    b.HasIndex("TenantId", "TemplateKey", "Channel")
                        .IsUnique()
                        .HasDatabaseName("idx_templates_unique");

                    b.ToTable("message_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "tpl-default-apt-created",
                            Active = true,
                            Channel = "whatsapp",
                            CreatedAt = new DateTime(2025, 12, 13, 17, 59, 22, 309, DateTimeKind.Utc).AddTicks(2054),
                            TemplateBody = "Olá {{client_name}}! Seu agendamento de {{service_name}} foi confirmado para {{scheduled_date}} às {{scheduled_time}}. Até lá!",
                            TemplateKey = "appointment_created",
                            UpdatedAt = new DateTime(2025, 12, 13, 17, 59, 22, 309, DateTimeKind.Utc).AddTicks(2057),
                            Variables = "[\"client_name\", \"service_name\", \"scheduled_date\", \"scheduled_time\"]"
                        },
                        new
                        {
                            Id = "tpl-default-apt-rescheduled",
                            Active = true,
                            Channel = "whatsapp",
                            CreatedAt = new DateTime(2025, 12, 13, 17, 59, 22, 309, DateTimeKind.Utc).AddTicks(2063),
                            TemplateBody = "Olá {{client_name}}! Seu agendamento foi alterado de {{old_date}} para {{new_date}} às {{new_time}}.",
                            TemplateKey = "appointment_rescheduled",
                            UpdatedAt = new DateTime(2025, 12, 13, 17, 59, 22, 309, DateTimeKind.Utc).AddTicks(2063),
                            Variables = "[\"client_name\", \"old_date\", \"new_date\", \"new_time\"]"
                        },
                        new
                        {
                            Id = "tpl-default-apt-cancelled",
                            Active = true,
                            Channel = "whatsapp",
                            CreatedAt = new DateTime(2025, 12, 13, 17, 59, 22, 309, DateTimeKind.Utc).AddTicks(2068),
                            TemplateBody = "Olá {{client_name}}! Seu agendamento de {{service_name}} do dia {{scheduled_date}} foi cancelado.",
                            TemplateKey = "appointment_cancelled",
                            UpdatedAt = new DateTime(2025, 12, 13, 17, 59, 22, 309, DateTimeKind.Utc).AddTicks(2068),
                            Variables = "[\"client_name\", \"service_name\", \"scheduled_date\"]"
                        },
                        new
                        {
                            Id = "tpl-default-reminder-24h",
                            Active = true,
                            Channel = "whatsapp",
                            CreatedAt = new DateTime(2025, 12, 13, 17, 59, 22, 309, DateTimeKind.Utc).AddTicks(2095),
                            TemplateBody = "Lembrete: Você tem agendamento amanhã às {{scheduled_time}} - {{service_name}}. Nos vemos lá!",
                            TemplateKey = "appointment_reminder_24h",
                            UpdatedAt = new DateTime(2025, 12, 13, 17, 59, 22, 309, DateTimeKind.Utc).AddTicks(2095),
                            Variables = "[\"scheduled_time\", \"service_name\"]"
                        },
                        new
                        {
                            Id = "tpl-default-reminder-1h",
                            Active = true,
                            Channel = "whatsapp",
                            CreatedAt = new DateTime(2025, 12, 13, 17, 59, 22, 309, DateTimeKind.Utc).AddTicks(2100),
                            TemplateBody = "Lembrete: Seu agendamento é daqui a 1 hora - {{service_name}}. Estamos te esperando!",
                            TemplateKey = "appointment_reminder_1h",
                            UpdatedAt = new DateTime(2025, 12, 13, 17, 59, 22, 309, DateTimeKind.Utc).AddTicks(2100),
                            Variables = "[\"service_name\"]"
                        });
                });

            modelBuilder.Entity("CommunicationService.Domain.Entities.ScheduledMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("message_type");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("SourceEntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_entity_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("SourceEntityId")
                        .HasDatabaseName("idx_scheduled_source");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_scheduled_tenant");

                    b.HasIndex("ScheduledAt", "Status")
                        .HasDatabaseName("idx_scheduled_status");

                    b.ToTable("scheduled_messages", (string)null);
                });

            modelBuilder.Entity("CommunicationService.Domain.Entities.MessageLog", b =>
                {
                    b.HasOne("CommunicationService.Domain.Entities.CommunicationEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CommunicationService.Domain.Entities.ScheduledMessage", b =>
                {
                    b.HasOne("CommunicationService.Domain.Entities.CommunicationEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
